name: "Publish Hex Elixir Package"
branding:
  icon: arrow-right-circle
  color: purple
description: "Publish an existing package to hex.pm when the version changes."
inputs:
  key:
    description: "Write key"
    required: true
  organization:
    description: "Optional organization to deploy package into"
    required: false
  name:
    description: "Name of package"
    required: true
  tag-release:
    description: "Create and push a git tag when the version changes"
    default: "true"
  working-directory:
    description: "Working directory to Mix project"
    default: "."
    required: false
outputs:
  local-version:
    description: "Version from project"
    value: ${{ steps.local-version.outputs.VERSION }}
  remote-version:
    description: "Version published to hex"
    value: ${{ steps.remote-version.outputs.VERSION }}
runs:
  using: "composite"
  steps:
    - name: Deps Get
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        mix deps.get
        mix compile
    - name: Authenticate
      shell: bash
      run: |
        echo "::group::Auth"
        echo "Authenticating"
        echo "::endgroup::"
        mix hex.config api_key ${{ inputs.key }}

    - name: Find local version
      id: local-version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        name=${{ inputs.name }}
        version=$(elixir -S mix run --no-start -e "IO.puts(Application.spec(:${name})[:vsn])")

        echo "::group::Local version"
        echo "${version}"
        echo "::endgroup::"
        echo "VERSION=${version}" >> $GITHUB_OUTPUT

    - name: Find remote version
      id: remote-version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        name=${{ inputs.name }}
        organization=${{ inputs.organization }}
        SEMVER_REGEX="^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(\\-[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?$"

        echo "::group::Remote version"

        if [[ -n "${organization}" ]]; then
          search=$(mix hex.info "${name}" --organization "${organization}")
        else
          search=$(mix hex.info "${name}")
        fi

        echo "name: ${name}"
        echo "hex.search: ${search}"
        remote_version=$(echo "${search}" | grep 'Releases: ' | awk '{print $2}' | tr -d ',')

        echo "remote version: ${remote_version}"
        echo "::endgroup::"
        echo "VERSION=${remote_version}" >> $GITHUB_OUTPUT

    - name: Verify versions
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        SEMVER_REGEX="^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(\\-[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?(\\+[0-9A-Za-z-]+(\\.[0-9A-Za-z-]+)*)?$"

        echo "::group::Versions"

        local_version=${{ steps.local-version.outputs.VERSION }}
        remote_version=${{ steps.remote-version.outputs.VERSION }}

        if [[ ! "${local_version}" =~ $SEMVER_REGEX ]]; then
          echo "::error::Unable to find local version ${local_version}"
          exit 1
        fi

        if [[ ! "${remote_version}" =~ $SEMVER_REGEX ]]; then
          echo "::error::Unable to find remote version ${remote_version}"
          exit 1
        fi

        echo "Project version: ${local_version}"
        echo "Released version: ${remote_version}"
        echo "::endgroup::"

    - name: Publish
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        local_version=${{ steps.local-version.outputs.VERSION }}
        remote_version=${{ steps.remote-version.outputs.VERSION }}
        organization=${{ inputs.organization }}

        echo "::group::Publish"

        if [[ "${local_version}" == "${remote_version}" ]]; then
          echo "Version has already been published"
          echo "Doing nothing"
          exit 0
        fi

        if [[ -n "$organization" ]]; then
          mix hex.publish --organization "$organization" --yes
        else
          mix hex.publish --yes
        fi

        echo "::endgroup::"
    - name: Tag release
      if: inputs.tag-release == 'true' && steps.local-version.outputs.VERSION != steps.remote-version.outputs.VERSION
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "::group::Tag release"

        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git tag -a "v${{steps.local-version.outputs.VERSION}}" -m "v{{steps.local-version.outputs.VERSION}}"
        git push --follow-tags

